### ISSUE TITLE
Install does not work on CentOS 6.0 box

### ISSUE THREAD

**Issue by mparker1001** [alunduil/pmort#2]
```
[mparker@mpprojects2 pmort]$ sudo python setup.py install
Traceback (most recent call last):
  File "setup.py", line 10, in <module>
    if sys.version_info.major < 3:
AttributeError: 'tuple' object has no attribute 'major'
```

**Comment by alunduil** [comment]
Could we try using a virtualenv to distribute this instead?  Getting compatibility across two major versions of python (heck even 3.2 vs 3.3) is non-trivial.  Let me know what you think and if you need any assistance getting it deployed with this model.

**Comment by alunduil** [comment]
Closing this since this is currently abandoned.
